[Vision_Model] 
vit_attention_probs_dropout_prob = 0.0
vit_initializer_range = 0.02
vit_hidden_dropout_prob = 0.0
vit_hidden_size = 768
vit_intermediate_size = 3072
vit_max_num_patches = 1600
vit_layer_norm_eps = 1e-12
vit_num_attention_heads = 12
vit_num_channels = 3
vit_num_hidden_layers = 4
vit_patch_size = 16
vit_qkv_bias = 1
vit_origin_patch_num = 14
map_x_patch_num = 20
map_y_patch_num = 20
vtm_patch_size = 16
patch_embed_size = 768
grid_size = 4
in_channels = 3
local_image_size = 224
local_patch_num = 196
num_stages = 4
sample_query_len = 32
pretrain_vit_path = /data/ZhangXinyue/Multi_Model/VLM_Model/vit-base-patch16-224

[Trajecotry_Model]
x_grid_num = 80
y_grid_num = 80
road_user_types = 4
encoder_dim = 128
gat_hid_dim = 256
gat_nhead = 4
num_relations = 4
top_k = 4
num_shared_experts = 3
num_independent_experts = 16
vtm_hidden_size = 768
vtm_num_attention_heads = 12
vtm_qkv_bias = 1
vtm_attention_dropout_prob = 0
vtm_hidden_dropout_prob = 0
vtm_intermediate_size = 3072
vtm_layer_norm_eps = 1e-12
vtm_num_hidden_layers = 6
vtm_modality_type_vocab_size = 2
traj_dec_hidden_size = 128
traj_modal_num = 1

[Data]
data_root = /data/ZhangXinyue/Multi_Model/data/inD-Location1-new
map_root = /data/ZhangXinyue/traj_vision_model_last/map_view/inD-location1.png
dataset = inD-new-v32-nocls
his_len = 20
pred_len = 20
small_ds = 0
node_num = 6
embed_scale = 1

[Train]
lr = 0.0001
lr_decay = 0.99
weight_decay = 0.01
batch_size = 32
epoch = 100
val_epoch = 5
test_epoch = 1
patience = 3
gpu = 6
nni = 0
save_result = 0
train_model = 1
load_model = 0
fine_tune = 0
model_root = ./logs
load_model_path = None
